services:
    backend:
        image: registry.digitalocean.com/tcup-alpha/backend:latest
        platform: linux/amd64
        build:
            context: .
            target: api-runner
        restart: unless-stopped
        env_file:
            - apps/backend/.env.development
        ports:
            - "3001:3001"

    caddy:
        image: registry.digitalocean.com/tcup-alpha/caddy:latest
        platform: linux/amd64
        build:
            context: .
            target: caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - $PWD/conf:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config

    directus:
        image: directus/directus:12.1.1
        platform: linux/amd64
        restart: unless-stopped
        ports:
            - 8055:8055
        volumes:
            - ./packages/extensions:/directus/extensions
        env_file:
            - .env.directus.prod
        environment:
            WEBSOCKETS_ENABLED: true

volumes:
  caddy_data:
  caddy_config:
