services:
    shared:
        build:
            context: .
            dockerfile: Dockerfile.dev
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
            - /app/packages/shared/node_modules
            - pnpm-store:/pnpm/store
        command: pnpm --filter shared dev

    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: builder
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
            - /app/apps/backend/node_modules
            - /app/apps/web/node_modules
            - pnpm-store:/pnpm/store
        env_file:
            - apps/web/.env.local
        ports:
            - "5173:5173"
            - "24678:24678"
        depends_on:
            shared:
                condition: service_started
        command: pnpm --filter web dev

    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: builder
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
            - /app/apps/backend/node_modules
            - /app/apps/web/node_modules
            - pnpm-store:/pnpm/store
        env_file:
            - apps/backend/.env.development
        ports:
            - "3001:3001"
        depends_on:
            shared:
                condition: service_started
        command: pnpm --filter backend dev

    directus:
        image: directus/directus:12.1.1
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        env_file:
            - .env.directus.local
        environment:
            WEBSOCKETS_ENABLED: true

volumes:
    pnpm-store:
