packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - browser-tabs-lock
  - core-js
  - core-js-pure
  - esbuild

onlyBuiltDependencies:
  - supabase

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  browser-tabs-lock: false
  core-js: false
  esbuild: true
  supabase: false
