packages:
  - apps/*
  - packages/extensions/*
  - packages/*

ignoredBuiltDependencies:
  - browser-tabs-lock
  - core-js
  - core-js-pure
  - esbuild

overrides:
  "@tiptap/core": "3.27.3"
  "@tiptap/pm": "3.27.3"
  prosemirror-model: "1.25.10"
  prosemirror-view: "1.42.0"
  prosemirror-state: "1.4.4"
  typescript: "5.9.3"

onlyBuiltDependencies:
  - supabase

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  browser-tabs-lock: false
  core-js: false
  esbuild: true
  supabase: false
  vue-demi: true