SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."add_reply_to_thread"("p_thread_id" bigint, "p_content" "text", "p_auth0_id" "text", "p_author" "text") RETURNS "json"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
    v_reply forum_messages;
    v_category text;
BEGIN
    -- Get the category from the parent thread
    SELECT category INTO v_category
    FROM forum_messages
    WHERE id = p_thread_id;

    -- Insert the reply with the same category as the parent
    INSERT INTO forum_messages (
        content,
        auth0_id,
        author,
        parent_id,
        category,
        is_thread_starter
    ) VALUES (
        p_content,
        p_auth0_id,
        p_author,
        p_thread_id,
        v_category,
        false
    )
    RETURNING * INTO v_reply;

    -- Update the thread's reply count and last_reply_at
    UPDATE forum_messages
    SET 
        reply_count = reply_count + 1,
        last_reply_at = NOW()
    WHERE id = p_thread_id;

    RETURN row_to_json(v_reply);
END;
$$;


ALTER FUNCTION "public"."add_reply_to_thread"("p_thread_id" bigint, "p_content" "text", "p_auth0_id" "text", "p_author" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."delete_thread_reactions"("thread_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Delete reactions to the main thread
  DELETE FROM user_reactions WHERE post_id = thread_id;
  
  -- Delete reactions to all replies in the thread
  DELETE FROM user_reactions 
  WHERE post_id IN (
    SELECT id FROM forum_messages WHERE parent_id = thread_id
  );
END;
$$;


ALTER FUNCTION "public"."delete_thread_reactions"("thread_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "id" integer NOT NULL,
    "user1" "text" NOT NULL,
    "user2" "text" NOT NULL,
    "latest_message" "jsonb",
    "latest_message_at" timestamp with time zone,
    "latest_message_id" integer,
    "unread_count_user1" integer DEFAULT 0,
    "unread_count_user2" integer DEFAULT 0
);


ALTER TABLE "public"."conversations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."conversations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."conversations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."conversations_id_seq" OWNED BY "public"."conversations"."id";



CREATE TABLE IF NOT EXISTS "public"."direct_messages" (
    "id" bigint NOT NULL,
    "sender_id" "text" NOT NULL,
    "recipient_id" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "read_at" timestamp with time zone,
    "images" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."direct_messages" OWNER TO "postgres";


ALTER TABLE "public"."direct_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."direct_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."forum_messages" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "auth0_id" character varying(255) NOT NULL,
    "author" "text",
    "category" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "is_edited" boolean DEFAULT false,
    "parent_id" bigint,
    "is_thread_starter" boolean DEFAULT false,
    "title" "text",
    "reply_count" integer DEFAULT 0,
    "last_reply_at" timestamp with time zone,
    "views" integer DEFAULT 0,
    "images" "jsonb" DEFAULT '[]'::"jsonb",
    "is_imported" boolean DEFAULT false,
    "imported_author_name" "text",
    "imported_date" "text",
    "imported_avatar_url" "text",
    CONSTRAINT "forum_messages_category_check" CHECK (("category" = ANY (ARRAY['General'::"text", 'Help'::"text", 'TCUP'::"text"])))
);


ALTER TABLE "public"."forum_messages" OWNER TO "postgres";


ALTER TABLE "public"."forum_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."forum_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "text" "text" NOT NULL,
    "channel" "text" NOT NULL,
    "user_id" "text" NOT NULL,
    "author_name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "text_search" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"english"'::"regconfig", "text")) STORED
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_reactions" (
    "id" bigint NOT NULL,
    "post_id" bigint,
    "user_id" "text" NOT NULL,
    "type" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."user_reactions" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."post_reactions" AS
 SELECT "user_reactions"."post_id",
    "user_reactions"."type",
    "count"(*) AS "count"
   FROM "public"."user_reactions"
  GROUP BY "user_reactions"."post_id", "user_reactions"."type";


ALTER TABLE "public"."post_reactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."post_tags" (
    "post_id" bigint NOT NULL,
    "tag_id" integer NOT NULL
);


ALTER TABLE "public"."post_tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tags_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."tags_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tags_id_seq" OWNED BY "public"."tags"."id";



CREATE TABLE IF NOT EXISTS "public"."test_messages" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "author" "text",
    "user_id" "text"
);


ALTER TABLE "public"."test_messages" OWNER TO "postgres";


ALTER TABLE "public"."test_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."thread_activity_view" AS
 SELECT "t"."id",
    "t"."content",
    "t"."auth0_id",
    "t"."author",
    "t"."category",
    "t"."created_at",
    "t"."updated_at",
    "t"."is_edited",
    "t"."parent_id",
    "t"."is_thread_starter",
    "t"."title",
    "t"."reply_count",
    "t"."last_reply_at",
    COALESCE("t"."last_reply_at", "t"."created_at") AS "latest_activity_at",
    "t"."views",
    "t"."images"
   FROM "public"."forum_messages" "t"
  WHERE ("t"."parent_id" IS NULL);


ALTER TABLE "public"."thread_activity_view" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."thread_listings" AS
 SELECT "fm"."id",
    "fm"."content",
    "fm"."auth0_id",
        CASE
            WHEN "fm"."is_imported" THEN "fm"."imported_author_name"
            ELSE "fm"."author"
        END AS "author",
    "fm"."category",
    "fm"."created_at",
    "fm"."updated_at",
    "fm"."is_edited",
    "fm"."parent_id",
    "fm"."is_thread_starter",
    "fm"."title",
    "fm"."reply_count",
    "fm"."last_reply_at",
    "fm"."views",
    "fm"."images",
    COALESCE("fm"."last_reply_at", "fm"."created_at") AS "latest_activity_at",
    "fm"."is_imported",
    "fm"."imported_date"
   FROM "public"."forum_messages" "fm"
  WHERE ("fm"."parent_id" IS NULL);


ALTER TABLE "public"."thread_listings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."thread_read_status" (
    "id" bigint NOT NULL,
    "auth0_id" "text" NOT NULL,
    "thread_id" bigint NOT NULL,
    "last_read_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."thread_read_status" OWNER TO "postgres";


ALTER TABLE "public"."thread_read_status" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."thread_read_status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."user_conversations" AS
 WITH "conversation_pairs" AS (
         SELECT LEAST("direct_messages"."sender_id", "direct_messages"."recipient_id") AS "user1",
            GREATEST("direct_messages"."sender_id", "direct_messages"."recipient_id") AS "user2"
           FROM "public"."direct_messages"
          GROUP BY LEAST("direct_messages"."sender_id", "direct_messages"."recipient_id"), GREATEST("direct_messages"."sender_id", "direct_messages"."recipient_id")
        ), "latest_messages" AS (
         SELECT LEAST("direct_messages"."sender_id", "direct_messages"."recipient_id") AS "user1",
            GREATEST("direct_messages"."sender_id", "direct_messages"."recipient_id") AS "user2",
            "max"("direct_messages"."created_at") AS "latest_message_at"
           FROM "public"."direct_messages"
          GROUP BY LEAST("direct_messages"."sender_id", "direct_messages"."recipient_id"), GREATEST("direct_messages"."sender_id", "direct_messages"."recipient_id")
        )
 SELECT "cp"."user1",
    "cp"."user2",
    "lm"."latest_message_at",
    ( SELECT "dm"."id"
           FROM "public"."direct_messages" "dm"
          WHERE (((("dm"."sender_id" = "cp"."user1") AND ("dm"."recipient_id" = "cp"."user2")) OR (("dm"."sender_id" = "cp"."user2") AND ("dm"."recipient_id" = "cp"."user1"))) AND ("dm"."created_at" = "lm"."latest_message_at"))
         LIMIT 1) AS "latest_message_id",
    ( SELECT "jsonb_build_object"('id', "dm"."id", 'sender_id', "dm"."sender_id", 'content', "dm"."content", 'created_at', "dm"."created_at", 'images', "dm"."images") AS "jsonb_build_object"
           FROM "public"."direct_messages" "dm"
          WHERE (((("dm"."sender_id" = "cp"."user1") AND ("dm"."recipient_id" = "cp"."user2")) OR (("dm"."sender_id" = "cp"."user2") AND ("dm"."recipient_id" = "cp"."user1"))) AND ("dm"."created_at" = "lm"."latest_message_at"))
         LIMIT 1) AS "latest_message",
    ( SELECT "count"(*) AS "count"
           FROM "public"."direct_messages" "dm"
          WHERE (("dm"."recipient_id" = "cp"."user1") AND ("dm"."sender_id" = "cp"."user2") AND ("dm"."read_at" IS NULL))) AS "unread_count_user1",
    ( SELECT "count"(*) AS "count"
           FROM "public"."direct_messages" "dm"
          WHERE (("dm"."recipient_id" = "cp"."user2") AND ("dm"."sender_id" = "cp"."user1") AND ("dm"."read_at" IS NULL))) AS "unread_count_user2"
   FROM ("conversation_pairs" "cp"
     JOIN "latest_messages" "lm" ON ((("cp"."user1" = "lm"."user1") AND ("cp"."user2" = "lm"."user2"))));


ALTER TABLE "public"."user_conversations" OWNER TO "postgres";


ALTER TABLE "public"."user_reactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_reactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text",
    "username" "text",
    "avatar_url" "text",
    "last_activity" timestamp with time zone,
    "register_date" timestamp with time zone,
    "user_state" "text",
    "message_count" integer,
    "receive_admin_email" boolean,
    "is_banned" boolean,
    "is_staff" boolean,
    "user_group_id" integer,
    "is_unregistered" boolean,
    "is_registered" boolean,
    "is_admin" boolean,
    "is_moderator" boolean,
    "is_tcup_member" boolean,
    "is_core_team_leader" boolean
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."conversations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."conversations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tags" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tags_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."conversations"
    ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."direct_messages"
    ADD CONSTRAINT "direct_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."forum_messages"
    ADD CONSTRAINT "forum_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."post_tags"
    ADD CONSTRAINT "post_tags_pkey" PRIMARY KEY ("post_id", "tag_id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_messages"
    ADD CONSTRAINT "test_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."thread_read_status"
    ADD CONSTRAINT "thread_read_status_auth0_id_thread_id_key" UNIQUE ("auth0_id", "thread_id");



ALTER TABLE ONLY "public"."thread_read_status"
    ADD CONSTRAINT "thread_read_status_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."conversations"
    ADD CONSTRAINT "unique_conversation" UNIQUE ("user1", "user2");



ALTER TABLE ONLY "public"."user_reactions"
    ADD CONSTRAINT "user_reactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE INDEX "direct_messages_created_at_idx" ON "public"."direct_messages" USING "btree" ("created_at");



CREATE INDEX "direct_messages_recipient_id_idx" ON "public"."direct_messages" USING "btree" ("recipient_id");



CREATE INDEX "direct_messages_sender_id_idx" ON "public"."direct_messages" USING "btree" ("sender_id");



CREATE INDEX "forum_messages_auth0_id_idx" ON "public"."forum_messages" USING "btree" ("auth0_id");



CREATE INDEX "forum_messages_category_idx" ON "public"."forum_messages" USING "btree" ("category");



CREATE INDEX "idx_direct_messages_created_at" ON "public"."direct_messages" USING "btree" ("created_at");



CREATE INDEX "idx_forum_messages_auth0_id" ON "public"."forum_messages" USING "btree" ("auth0_id");



CREATE INDEX "idx_forum_messages_created_at" ON "public"."forum_messages" USING "btree" ("created_at");



CREATE INDEX "idx_forum_messages_id" ON "public"."forum_messages" USING "btree" ("id");



CREATE INDEX "idx_id" ON "public"."direct_messages" USING "btree" ("id");



CREATE INDEX "idx_parent_id" ON "public"."forum_messages" USING "btree" ("parent_id");



CREATE INDEX "idx_thread_read_status_auth0_id" ON "public"."thread_read_status" USING "btree" ("auth0_id");



CREATE INDEX "idx_thread_read_status_thread_id" ON "public"."thread_read_status" USING "btree" ("thread_id");



CREATE INDEX "idx_thread_starter" ON "public"."forum_messages" USING "btree" ("is_thread_starter");



CREATE INDEX "messages_text_search_idx" ON "public"."messages" USING "gin" ("text_search");



ALTER TABLE ONLY "public"."forum_messages"
    ADD CONSTRAINT "forum_messages_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."forum_messages"("id");



ALTER TABLE ONLY "public"."post_tags"
    ADD CONSTRAINT "post_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."forum_messages"("id");



ALTER TABLE ONLY "public"."post_tags"
    ADD CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id");



ALTER TABLE ONLY "public"."thread_read_status"
    ADD CONSTRAINT "thread_read_status_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "public"."forum_messages"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_reactions"
    ADD CONSTRAINT "user_reactions_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."forum_messages"("id");



CREATE POLICY "Allow authenticated users to insert conversations" ON "public"."conversations" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow authenticated users to read conversations" ON "public"."conversations" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow authenticated users to update conversations" ON "public"."conversations" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Anyone can read messages" ON "public"."messages" FOR SELECT USING (true);



CREATE POLICY "Authenticated users can insert messages" ON "public"."messages" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable read access for authenticated users" ON "public"."test_messages" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."conversations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_messages" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "thread_read_status_auth" ON "public"."thread_read_status" TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."add_reply_to_thread"("p_thread_id" bigint, "p_content" "text", "p_auth0_id" "text", "p_author" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."add_reply_to_thread"("p_thread_id" bigint, "p_content" "text", "p_auth0_id" "text", "p_author" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."add_reply_to_thread"("p_thread_id" bigint, "p_content" "text", "p_auth0_id" "text", "p_author" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."delete_thread_reactions"("thread_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."delete_thread_reactions"("thread_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_thread_reactions"("thread_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."conversations" TO "anon";
GRANT ALL ON TABLE "public"."conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."conversations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."conversations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."conversations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."conversations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."direct_messages" TO "anon";
GRANT ALL ON TABLE "public"."direct_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."direct_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."direct_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."direct_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."direct_messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."forum_messages" TO "anon";
GRANT ALL ON TABLE "public"."forum_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."forum_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."forum_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."forum_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."forum_messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_reactions" TO "anon";
GRANT ALL ON TABLE "public"."user_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."user_reactions" TO "service_role";



GRANT ALL ON TABLE "public"."post_reactions" TO "anon";
GRANT ALL ON TABLE "public"."post_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."post_reactions" TO "service_role";



GRANT ALL ON TABLE "public"."post_tags" TO "anon";
GRANT ALL ON TABLE "public"."post_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."post_tags" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_messages" TO "anon";
GRANT ALL ON TABLE "public"."test_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."test_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."thread_activity_view" TO "anon";
GRANT ALL ON TABLE "public"."thread_activity_view" TO "authenticated";
GRANT ALL ON TABLE "public"."thread_activity_view" TO "service_role";



GRANT ALL ON TABLE "public"."thread_listings" TO "anon";
GRANT ALL ON TABLE "public"."thread_listings" TO "authenticated";
GRANT ALL ON TABLE "public"."thread_listings" TO "service_role";



GRANT ALL ON TABLE "public"."thread_read_status" TO "anon";
GRANT ALL ON TABLE "public"."thread_read_status" TO "authenticated";
GRANT ALL ON TABLE "public"."thread_read_status" TO "service_role";



GRANT ALL ON SEQUENCE "public"."thread_read_status_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."thread_read_status_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."thread_read_status_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_conversations" TO "anon";
GRANT ALL ON TABLE "public"."user_conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."user_conversations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_reactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_reactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_reactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























