CREATE TABLE IF NOT EXISTS "public"."users" (
    id         integer generated by default as identity (maxvalue 2147483647) primary key,
    auth0_id   varchar(255) not null unique,
    username   varchar(255),
    avatar_url text,
    created_at timestamp   default CURRENT_TIMESTAMP,
    email      text,
    role       varchar(20) default 'user'::character varying,
    tagline    varchar,
    bio        varchar
);


ALTER TABLE "public"."users" OWNER TO "postgres";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";
