/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as CampaignRouteRouteImport } from './routes/campaign/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as CampaignSlugRouteImport } from './routes/campaign/$slug'
import { Route as AppUpdatesRouteRouteImport } from './routes/_app/updates/route'
import { Route as AppThreadsRouteRouteImport } from './routes/_app/threads/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppUpdatesIndexRouteImport } from './routes/_app/updates/index'
import { Route as AppThreadsIndexRouteImport } from './routes/_app/threads/index'
import { Route as AppProtectedIndexRouteImport } from './routes/_app/protected/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppUpdatesIdRouteImport } from './routes/_app/updates/$id'
import { Route as AppThreadsCreateRouteImport } from './routes/_app/threads/create'
import { Route as AppThreadsIdRouteImport } from './routes/_app/threads/$id'
import { Route as AppProfileMeRouteImport } from './routes/_app/profile/me'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile/edit'
import { Route as AppProfileIdRouteImport } from './routes/_app/profile/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRouteRoute = CampaignRouteRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const CampaignSlugRoute = CampaignSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const AppUpdatesRouteRoute = AppUpdatesRouteRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppThreadsRouteRoute = AppThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpdatesIndexRoute = AppUpdatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUpdatesRouteRoute,
} as any)
const AppThreadsIndexRoute = AppThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppProtectedIndexRoute = AppProtectedIndexRouteImport.update({
  id: '/protected/',
  path: '/protected/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppUpdatesIdRoute = AppUpdatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppUpdatesRouteRoute,
} as any)
const AppThreadsCreateRoute = AppThreadsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppThreadsIdRoute = AppThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppProfileMeRoute = AppProfileMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/colors': typeof ColorsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRouteRouteWithChildren
  '/threads': typeof AppThreadsRouteRouteWithChildren
  '/updates': typeof AppUpdatesRouteRouteWithChildren
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign/': typeof CampaignIndexRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/me': typeof AppProfileMeRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/threads/create': typeof AppThreadsCreateRoute
  '/updates/$id': typeof AppUpdatesIdRoute
  '/profile/': typeof AppProfileIndexRoute
  '/protected/': typeof AppProtectedIndexRoute
  '/threads/': typeof AppThreadsIndexRoute
  '/updates/': typeof AppUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/colors': typeof ColorsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign': typeof CampaignIndexRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/me': typeof AppProfileMeRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/threads/create': typeof AppThreadsCreateRoute
  '/updates/$id': typeof AppUpdatesIdRoute
  '/profile': typeof AppProfileIndexRoute
  '/protected': typeof AppProtectedIndexRoute
  '/threads': typeof AppThreadsIndexRoute
  '/updates': typeof AppUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/colors': typeof ColorsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRouteRouteWithChildren
  '/_app/threads': typeof AppThreadsRouteRouteWithChildren
  '/_app/updates': typeof AppUpdatesRouteRouteWithChildren
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign/': typeof CampaignIndexRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/profile/me': typeof AppProfileMeRoute
  '/_app/threads/$id': typeof AppThreadsIdRoute
  '/_app/threads/create': typeof AppThreadsCreateRoute
  '/_app/updates/$id': typeof AppUpdatesIdRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/protected/': typeof AppProtectedIndexRoute
  '/_app/threads/': typeof AppThreadsIndexRoute
  '/_app/updates/': typeof AppUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/callback'
    | '/colors'
    | '/faq'
    | '/login'
    | '/profile'
    | '/threads'
    | '/updates'
    | '/campaign/$slug'
    | '/campaign/'
    | '/profile/$id'
    | '/profile/edit'
    | '/profile/me'
    | '/threads/$id'
    | '/threads/create'
    | '/updates/$id'
    | '/profile/'
    | '/protected/'
    | '/threads/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/colors'
    | '/faq'
    | '/login'
    | '/campaign/$slug'
    | '/campaign'
    | '/profile/$id'
    | '/profile/edit'
    | '/profile/me'
    | '/threads/$id'
    | '/threads/create'
    | '/updates/$id'
    | '/profile'
    | '/protected'
    | '/threads'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/campaign'
    | '/callback'
    | '/colors'
    | '/faq'
    | '/login'
    | '/_app/profile'
    | '/_app/threads'
    | '/_app/updates'
    | '/campaign/$slug'
    | '/campaign/'
    | '/_app/profile/$id'
    | '/_app/profile/edit'
    | '/_app/profile/me'
    | '/_app/threads/$id'
    | '/_app/threads/create'
    | '/_app/updates/$id'
    | '/_app/profile/'
    | '/_app/protected/'
    | '/_app/threads/'
    | '/_app/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CampaignRouteRoute: typeof CampaignRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ColorsRoute: typeof ColorsRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/campaign/$slug': {
      id: '/campaign/$slug'
      path: '/$slug'
      fullPath: '/campaign/$slug'
      preLoaderRoute: typeof CampaignSlugRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/threads': {
      id: '/_app/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AppThreadsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/updates/': {
      id: '/_app/updates/'
      path: '/'
      fullPath: '/updates/'
      preLoaderRoute: typeof AppUpdatesIndexRouteImport
      parentRoute: typeof AppUpdatesRouteRoute
    }
    '/_app/threads/': {
      id: '/_app/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof AppThreadsIndexRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/protected/': {
      id: '/_app/protected/'
      path: '/protected'
      fullPath: '/protected/'
      preLoaderRoute: typeof AppProtectedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/updates/$id': {
      id: '/_app/updates/$id'
      path: '/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof AppUpdatesIdRouteImport
      parentRoute: typeof AppUpdatesRouteRoute
    }
    '/_app/threads/create': {
      id: '/_app/threads/create'
      path: '/create'
      fullPath: '/threads/create'
      preLoaderRoute: typeof AppThreadsCreateRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/threads/$id': {
      id: '/_app/threads/$id'
      path: '/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof AppThreadsIdRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/profile/me': {
      id: '/_app/profile/me'
      path: '/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof AppProfileMeRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
  }
}

interface AppProfileRouteRouteChildren {
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileMeRoute: typeof AppProfileMeRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileMeRoute: AppProfileMeRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppThreadsRouteRouteChildren {
  AppThreadsIdRoute: typeof AppThreadsIdRoute
  AppThreadsCreateRoute: typeof AppThreadsCreateRoute
  AppThreadsIndexRoute: typeof AppThreadsIndexRoute
}

const AppThreadsRouteRouteChildren: AppThreadsRouteRouteChildren = {
  AppThreadsIdRoute: AppThreadsIdRoute,
  AppThreadsCreateRoute: AppThreadsCreateRoute,
  AppThreadsIndexRoute: AppThreadsIndexRoute,
}

const AppThreadsRouteRouteWithChildren = AppThreadsRouteRoute._addFileChildren(
  AppThreadsRouteRouteChildren,
)

interface AppUpdatesRouteRouteChildren {
  AppUpdatesIdRoute: typeof AppUpdatesIdRoute
  AppUpdatesIndexRoute: typeof AppUpdatesIndexRoute
}

const AppUpdatesRouteRouteChildren: AppUpdatesRouteRouteChildren = {
  AppUpdatesIdRoute: AppUpdatesIdRoute,
  AppUpdatesIndexRoute: AppUpdatesIndexRoute,
}

const AppUpdatesRouteRouteWithChildren = AppUpdatesRouteRoute._addFileChildren(
  AppUpdatesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppThreadsRouteRoute: typeof AppThreadsRouteRouteWithChildren
  AppUpdatesRouteRoute: typeof AppUpdatesRouteRouteWithChildren
  AppProtectedIndexRoute: typeof AppProtectedIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppThreadsRouteRoute: AppThreadsRouteRouteWithChildren,
  AppUpdatesRouteRoute: AppUpdatesRouteRouteWithChildren,
  AppProtectedIndexRoute: AppProtectedIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CampaignRouteRouteChildren {
  CampaignSlugRoute: typeof CampaignSlugRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteRouteChildren: CampaignRouteRouteChildren = {
  CampaignSlugRoute: CampaignSlugRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteRouteWithChildren = CampaignRouteRoute._addFileChildren(
  CampaignRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CampaignRouteRoute: CampaignRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ColorsRoute: ColorsRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
