/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppThreadsRouteRouteImport } from './routes/_app/threads/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppThreadsIndexRouteImport } from './routes/_app/threads/index'
import { Route as AppProtectedIndexRouteImport } from './routes/_app/protected/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppThreadsCreateRouteImport } from './routes/_app/threads/create'
import { Route as AppThreadsIdRouteImport } from './routes/_app/threads/$id'
import { Route as AppProfileMeRouteImport } from './routes/_app/profile/me'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile/edit'
import { Route as AppProfileIdRouteImport } from './routes/_app/profile/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThreadsRouteRoute = AppThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsIndexRoute = AppThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppProtectedIndexRoute = AppProtectedIndexRouteImport.update({
  id: '/protected/',
  path: '/protected/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppThreadsCreateRoute = AppThreadsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppThreadsIdRoute = AppThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppProfileMeRoute = AppProfileMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRouteRouteWithChildren
  '/threads': typeof AppThreadsRouteRouteWithChildren
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/me': typeof AppProfileMeRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/threads/create': typeof AppThreadsCreateRoute
  '/profile/': typeof AppProfileIndexRoute
  '/protected/': typeof AppProtectedIndexRoute
  '/threads/': typeof AppThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/me': typeof AppProfileMeRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/threads/create': typeof AppThreadsCreateRoute
  '/profile': typeof AppProfileIndexRoute
  '/protected': typeof AppProtectedIndexRoute
  '/threads': typeof AppThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRouteRouteWithChildren
  '/_app/threads': typeof AppThreadsRouteRouteWithChildren
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/profile/me': typeof AppProfileMeRoute
  '/_app/threads/$id': typeof AppThreadsIdRoute
  '/_app/threads/create': typeof AppThreadsCreateRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/protected/': typeof AppProtectedIndexRoute
  '/_app/threads/': typeof AppThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/profile'
    | '/threads'
    | '/profile/$id'
    | '/profile/edit'
    | '/profile/me'
    | '/threads/$id'
    | '/threads/create'
    | '/profile/'
    | '/protected/'
    | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/profile/$id'
    | '/profile/edit'
    | '/profile/me'
    | '/threads/$id'
    | '/threads/create'
    | '/profile'
    | '/protected'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/callback'
    | '/login'
    | '/_app/profile'
    | '/_app/threads'
    | '/_app/profile/$id'
    | '/_app/profile/edit'
    | '/_app/profile/me'
    | '/_app/threads/$id'
    | '/_app/threads/create'
    | '/_app/profile/'
    | '/_app/protected/'
    | '/_app/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/threads': {
      id: '/_app/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AppThreadsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/': {
      id: '/_app/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof AppThreadsIndexRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/protected/': {
      id: '/_app/protected/'
      path: '/protected'
      fullPath: '/protected/'
      preLoaderRoute: typeof AppProtectedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/threads/create': {
      id: '/_app/threads/create'
      path: '/create'
      fullPath: '/threads/create'
      preLoaderRoute: typeof AppThreadsCreateRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/threads/$id': {
      id: '/_app/threads/$id'
      path: '/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof AppThreadsIdRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/_app/profile/me': {
      id: '/_app/profile/me'
      path: '/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof AppProfileMeRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
  }
}

interface AppProfileRouteRouteChildren {
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileMeRoute: typeof AppProfileMeRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileMeRoute: AppProfileMeRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppThreadsRouteRouteChildren {
  AppThreadsIdRoute: typeof AppThreadsIdRoute
  AppThreadsCreateRoute: typeof AppThreadsCreateRoute
  AppThreadsIndexRoute: typeof AppThreadsIndexRoute
}

const AppThreadsRouteRouteChildren: AppThreadsRouteRouteChildren = {
  AppThreadsIdRoute: AppThreadsIdRoute,
  AppThreadsCreateRoute: AppThreadsCreateRoute,
  AppThreadsIndexRoute: AppThreadsIndexRoute,
}

const AppThreadsRouteRouteWithChildren = AppThreadsRouteRoute._addFileChildren(
  AppThreadsRouteRouteChildren,
)

interface AppRouteChildren {
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppThreadsRouteRoute: typeof AppThreadsRouteRouteWithChildren
  AppProtectedIndexRoute: typeof AppProtectedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppThreadsRouteRoute: AppThreadsRouteRouteWithChildren,
  AppProtectedIndexRoute: AppProtectedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
