CREATE TYPE "user_role" AS ENUM('user', 'admin', 'moderator', 'superadmin');--> statement-breakpoint
CREATE TABLE "conversation_participants" (
	"conversationId" integer,
	"userId" integer,
	CONSTRAINT "conversation_participants_conversationId_userId_pk" PRIMARY KEY("userId","conversationId")
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" serial PRIMARY KEY
);
--> statement-breakpoint
CREATE TABLE "post_reactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_reactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"type" varchar(12) NOT NULL,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "post_tags" (
	"post_id" integer,
	"tag_id" integer,
	CONSTRAINT "post_tags_pkey" PRIMARY KEY("tag_id","post_id")
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" jsonb NOT NULL,
	"author_id" integer NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp,
	"is_edited" boolean DEFAULT false,
	"parent_id" integer,
	"title" text,
	"images" jsonb DEFAULT '[]',
	"is_imported" boolean DEFAULT false,
	"imported_author_name" text,
	"imported_date" text,
	"imported_avatar_url" text,
	CONSTRAINT "thread_starter_has_title" CHECK ((parent_id IS NOT NULL) OR (title IS NOT NULL)),
	CONSTRAINT "no_self_reference" CHECK (parent_id <> id)
);
--> statement-breakpoint
CREATE TABLE "private_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"sender_id" integer NOT NULL,
	"content" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"images" jsonb DEFAULT '[]'
);
--> statement-breakpoint
CREATE TABLE "tags" (
	"id" serial PRIMARY KEY,
	"name" text NOT NULL CONSTRAINT "tags_name_key" UNIQUE,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "thread_read_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thread_read_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"thread_id" integer NOT NULL,
	"last_read_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
	CONSTRAINT "thread_read_status_user_id_thread_id_key" UNIQUE("user_id","thread_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"username" varchar(255) NOT NULL,
	"avatar_url" text,
	"auth0_id" varchar(255) NOT NULL CONSTRAINT "users_auth0_id_key" UNIQUE,
	"bio" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"role" "user_role" DEFAULT 'user'::"user_role" NOT NULL,
	"tagline" text
);
--> statement-breakpoint
CREATE INDEX "forum_messages_authorid_idx" ON "posts" ("author_id");--> statement-breakpoint
CREATE INDEX "forum_messages_id_authorid_idx" ON "posts" ("id","author_id");--> statement-breakpoint
CREATE INDEX "idx_parent_id" ON "posts" ("parent_id");--> statement-breakpoint
CREATE INDEX "direct_messages_sender_id_idx" ON "private_messages" ("sender_id");--> statement-breakpoint
CREATE INDEX "idx_direct_messages_created_at" ON "private_messages" ("created_at");--> statement-breakpoint
CREATE INDEX "idx_thread_read_status_thread_id" ON "thread_read_status" ("thread_id");--> statement-breakpoint
CREATE INDEX "idx_thread_read_status_user_id" ON "thread_read_status" ("user_id");--> statement-breakpoint
CREATE INDEX "users_id_auth0id_idx" ON "users" ("id","auth0_id");--> statement-breakpoint
CREATE INDEX "users_username_idx" ON "users" ("username");--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversationId_conversations_id_fk" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "post_reactions" ADD CONSTRAINT "user_reactions_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "post_reactions" ADD CONSTRAINT "user_reactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id");--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tags"("id");--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_user_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "forum_messages_user_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "forum_messages_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "posts"("id");--> statement-breakpoint
ALTER TABLE "private_messages" ADD CONSTRAINT "private_messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "private_messages" ADD CONSTRAINT "private_messages_sender_id_users_id_fk" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "thread_read_status" ADD CONSTRAINT "thread_read_status_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "thread_read_status" ADD CONSTRAINT "thread_read_status_thread_id_posts_id_fk" FOREIGN KEY ("thread_id") REFERENCES "posts"("id") ON DELETE CASCADE;--> statement-breakpoint
CREATE VIEW "posts_with_replies" AS (
    select
      threads.*,
      thread_authors.avatar_url as author_avatar,
      thread_authors.username as author_name,
      coalesce(thread_tags.tags, '[]'::json) as tags,
      replies.latest_reply_date,
      replies.latest_reply_author,
      replies.latest_reply_author_id,
      replies.latest_reply_author_avatar,
      replies_count.reply_count
    from
      public.posts as threads
      left join public.users as thread_authors on threads.author_id = thread_authors.id
      left join (
        select pt.post_id,
          json_agg(
            json_build_object(
              'id', t.id,
              'name', t.name,
              'description', t.description
            )
          ) as tags
        from public.post_tags pt
          join public.tags t on pt.tag_id = t.id
        group by pt.post_id
      ) as thread_tags on thread_tags.post_id = threads.id
      left join (
        select distinct
          on (m.parent_id) m.parent_id,
          m.author_id as latest_reply_author_id,
          u.username as latest_reply_author,
          u.avatar_url as latest_reply_author_avatar,
          m.created_at as latest_reply_date
        from
          public.posts m
          left join public.users u on u.id = m.author_id
        where
          m.parent_id is not null
        order by
          m.parent_id,
          m.created_at desc
      ) as replies on replies.parent_id = threads.id
      left join (
        select
          parent_id,
          count(*) as reply_count
        from
          public.posts
        where
          parent_id is not null
        group by
          parent_id
      ) as replies_count on replies_count.parent_id = threads.id
    where
      threads.parent_id is null
    order by
      coalesce(replies.latest_reply_date, threads.created_at) desc
    );