create extension if not exists "pg_net" with schema "extensions";

alter table "public"."users" drop column "is_admin";

alter table "public"."users" drop column "is_banned";

alter table "public"."users" drop column "is_core_team_leader";

alter table "public"."users" drop column "is_moderator";

alter table "public"."users" drop column "is_registered";

alter table "public"."users" drop column "is_staff";

alter table "public"."users" drop column "is_tcup_member";

alter table "public"."users" drop column "is_unregistered";

alter table "public"."users" drop column "last_activity";

alter table "public"."users" drop column "message_count";

alter table "public"."users" drop column "receive_admin_email";

alter table "public"."users" drop column "register_date";

alter table "public"."users" drop column "user_group_id";

alter table "public"."users" drop column "user_state";

alter table "public"."users" add column "auth0_id" character varying(255) not null;

alter table "public"."users" add column "bio" character varying;

alter table "public"."users" add column "created_at" timestamp without time zone default CURRENT_TIMESTAMP;

alter table "public"."users" add column "role" character varying(20) default 'user'::character varying;

alter table "public"."users" add column "tagline" character varying;

alter table "public"."users" alter column "id" drop default;

alter table "public"."users" alter column "id" set data type integer using 0;

alter table "public"."users" alter column "id" add generated by default as identity;

alter table "public"."users" alter column "username" set data type character varying(255) using "username"::character varying(255);

CREATE UNIQUE INDEX users_auth0_id_key ON public.users USING btree (auth0_id);

alter table "public"."users" add constraint "users_auth0_id_key" UNIQUE using index "users_auth0_id_key";


