/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as ProtectedIndexRouteImport } from './routes/protected/index'
import { Route as ThreadsIdRouteImport } from './routes/threads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/protected/',
  path: '/protected/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/protected/': typeof ProtectedIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/protected': typeof ProtectedIndexRoute
  '/threads': typeof ThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/protected/': typeof ProtectedIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/threads/$id' | '/protected/' | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/threads/$id' | '/protected' | '/threads'
  id: '__root__' | '/' | '/threads/$id' | '/protected/' | '/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadsIdRoute: typeof ThreadsIdRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/': {
      id: '/protected/'
      path: '/protected'
      fullPath: '/protected/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadsIdRoute: ThreadsIdRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
