/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteRouteImport } from './routes/threads/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as ProtectedIndexRouteImport } from './routes/protected/index'
import { Route as ThreadsIdRouteImport } from './routes/threads/$id'

const ThreadsRouteRoute = ThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadsRouteRoute,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/protected/',
  path: '/protected/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThreadsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/threads': typeof ThreadsRouteRouteWithChildren
  '/threads/$id': typeof ThreadsIdRoute
  '/protected/': typeof ProtectedIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/protected': typeof ProtectedIndexRoute
  '/threads': typeof ThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/threads': typeof ThreadsRouteRouteWithChildren
  '/threads/$id': typeof ThreadsIdRoute
  '/protected/': typeof ProtectedIndexRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/threads' | '/threads/$id' | '/protected/' | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/threads/$id' | '/protected' | '/threads'
  id:
    | '__root__'
    | '/'
    | '/threads'
    | '/threads/$id'
    | '/protected/'
    | '/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadsRouteRoute: typeof ThreadsRouteRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof ThreadsRouteRoute
    }
    '/protected/': {
      id: '/protected/'
      path: '/protected'
      fullPath: '/protected/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof ThreadsRouteRoute
    }
  }
}

interface ThreadsRouteRouteChildren {
  ThreadsIdRoute: typeof ThreadsIdRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

const ThreadsRouteRouteChildren: ThreadsRouteRouteChildren = {
  ThreadsIdRoute: ThreadsIdRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}

const ThreadsRouteRouteWithChildren = ThreadsRouteRoute._addFileChildren(
  ThreadsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadsRouteRoute: ThreadsRouteRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
